# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
# Third Party
import caikit_runtime_train_pb2 as caikit__runtime__train__pb2
import grpc


class SampleLibTrainingServiceStub(object):
    """The greeting service definition."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrainHello = channel.unary_unary(
            "/helloworld.SampleLibTrainingService/TrainHello",
            request_serializer=caikit__runtime__train__pb2.HelloTrainRequest.SerializeToString,
            response_deserializer=caikit__runtime__train__pb2.HelloTrainReply.FromString,
        )


class SampleLibTrainingServiceServicer(object):
    """The greeting service definition."""

    def TrainHello(self, request, context):
        """Sends a greeting"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_SampleLibTrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "TrainHello": grpc.unary_unary_rpc_method_handler(
            servicer.TrainHello,
            request_deserializer=caikit__runtime__train__pb2.HelloTrainRequest.FromString,
            response_serializer=caikit__runtime__train__pb2.HelloTrainReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "helloworld.SampleLibTrainingService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class SampleLibTrainingService(object):
    """The greeting service definition."""

    @staticmethod
    def TrainHello(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/helloworld.SampleLibTrainingService/TrainHello",
            caikit__runtime__train__pb2.HelloTrainRequest.SerializeToString,
            caikit__runtime__train__pb2.HelloTrainReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
