# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: caikit_runtime_train.proto
"""Generated protocol buffer code."""
# Third Party
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1a\x63\x61ikit_runtime_train.proto\x12\nhelloworld"!\n\x11HelloTrainRequest\x12\x0c\n\x04name\x18\x01 \x01(\t""\n\x0fHelloTrainReply\x12\x0f\n\x07message\x18\x01 \x01(\t2f\n\x18SampleLibTrainingService\x12J\n\nTrainHello\x12\x1d.helloworld.HelloTrainRequest\x1a\x1b.helloworld.HelloTrainReply"\x00\x62\x06proto3'
)


_HELLOTRAINREQUEST = DESCRIPTOR.message_types_by_name["HelloTrainRequest"]
_HELLOTRAINREPLY = DESCRIPTOR.message_types_by_name["HelloTrainReply"]
HelloTrainRequest = _reflection.GeneratedProtocolMessageType(
    "HelloTrainRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _HELLOTRAINREQUEST,
        "__module__": "caikit_runtime_train_pb2"
        # @@protoc_insertion_point(class_scope:helloworld.HelloTrainRequest)
    },
)
_sym_db.RegisterMessage(HelloTrainRequest)

HelloTrainReply = _reflection.GeneratedProtocolMessageType(
    "HelloTrainReply",
    (_message.Message,),
    {
        "DESCRIPTOR": _HELLOTRAINREPLY,
        "__module__": "caikit_runtime_train_pb2"
        # @@protoc_insertion_point(class_scope:helloworld.HelloTrainReply)
    },
)
_sym_db.RegisterMessage(HelloTrainReply)

_SAMPLELIBTRAININGSERVICE = DESCRIPTOR.services_by_name["SampleLibTrainingService"]
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    _HELLOTRAINREQUEST._serialized_start = 42
    _HELLOTRAINREQUEST._serialized_end = 75
    _HELLOTRAINREPLY._serialized_start = 77
    _HELLOTRAINREPLY._serialized_end = 111
    _SAMPLELIBTRAININGSERVICE._serialized_start = 113
    _SAMPLELIBTRAININGSERVICE._serialized_end = 215
# @@protoc_insertion_point(module_scope)
